apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mongo-api
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mongo-api
  template:
    metadata:
      labels:
        app: go-mongo-api
    spec:
      containers:
        - name: go-mongo-api
          image: tonytran1997/go-mongo-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGO_URI
              value: "mongodb-service:27017"
            - name: MONGO_DB
              value: "user_management"
            - name: MONGO_COLLECTION
              value: "users"
