apiVersion: v1
kind: Service
metadata:
  name: go-mongo-api-service
  namespace: staging
spec:
  selector:
    app: go-mongo-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
